Repository mulmagi/server, pull requests merged in 2023-12, with the labels that each got.

#95 Feat: 푸시 알림 거부 기능 구현
  src/main/java/shop/mulmagi/app/exception/ResponseMessage.java
  src/main/java/shop/mulmagi/app/repository/UserRepository.java
  src/main/java/shop/mulmagi/app/service/NotificationService.java
  src/main/java/shop/mulmagi/app/service/impl/NotificationServiceImpl.java
  src/main/java/shop/mulmagi/app/web/controller/NotificationController.java
Labels: enhancement

#105 Update: 로그인 함수 수정
  src/main/java/shop/mulmagi/app/config/SecurityConfig.java
  src/main/java/shop/mulmagi/app/dao/CustomUserDetails.java
  src/main/java/shop/mulmagi/app/domain/RefreshToken.java
  src/main/java/shop/mulmagi/app/domain/User.java
  src/main/java/shop/mulmagi/app/exception/ResponseMessage.java
  src/main/java/shop/mulmagi/app/repository/RefreshTokenRepository.java
  src/main/java/shop/mulmagi/app/service/UserService.java
  src/main/java/shop/mulmagi/app/service/impl/UserServiceImpl.java
  src/main/java/shop/mulmagi/app/util/JwtUtil.java
  src/main/java/shop/mulmagi/app/web/controller/UserController.java
  src/main/java/shop/mulmagi/app/web/dto/UserDto.java
Labels: Refactor

#114 Feat: FirebaseToken 검증 단계 추가
  src/main/java/shop/mulmagi/app/service/NotificationService.java
  src/main/java/shop/mulmagi/app/service/impl/NotificationServiceImpl.java
  src/main/java/shop/mulmagi/app/web/controller/NotificationController.java
Labels: enhancement

#115 Refactor: ReportService rental ID 받도록 변경 #110
  src/main/java/shop/mulmagi/app/repository/RentalRepository.java
  src/main/java/shop/mulmagi/app/service/impl/ReportServiceImpl.java
  src/main/java/shop/mulmagi/app/web/controller/ReportController.java
Labels: Refactor

#123 !HOTFIX: LocalDateTime 직렬화 설정 #122
  build.gradle
  src/main/java/shop/mulmagi/app/domain/base/BaseEntity.java
  src/main/java/shop/mulmagi/app/web/dto/MessageDto.java
  src/main/java/shop/mulmagi/app/web/dto/MessageResponseDto.java
Labels: bug

#125 !HOTFIX: 채팅 테스트 경로 수정 #124
  src/main/java/shop/mulmagi/app/web/controller/ChatTestController.java
  src/main/java/shop/mulmagi/app/web/dto/MessageDto.java
  src/main/java/shop/mulmagi/app/web/dto/MessageResponseDto.java
Labels: bug

#126 Feat: 이용 내역 화면 불러오기
  src/main/java/shop/mulmagi/app/exception/CustomExceptions.java
  src/main/java/shop/mulmagi/app/exception/ResponseMessage.java
  src/main/java/shop/mulmagi/app/repository/RentalRepository.java
  src/main/java/shop/mulmagi/app/service/UserService.java
  src/main/java/shop/mulmagi/app/service/impl/UserServiceImpl.java
  src/main/java/shop/mulmagi/app/web/controller/UserController.java
Labels: enhancement

#127 Feat: Authentication을 이용해서 api 접근을 제한하는 기능
  .gitignore
  build.gradle
  src/main/java/shop/mulmagi/app/config/SecurityConfig.java
  src/main/java/shop/mulmagi/app/dao/CustomUserDetails.java
  src/main/java/shop/mulmagi/app/domain/User.java
  src/main/java/shop/mulmagi/app/exception/CustomExceptions.java
  src/main/java/shop/mulmagi/app/exception/ResponseMessage.java
  src/main/java/shop/mulmagi/app/filter/JwtRequestFilter.java
  src/main/java/shop/mulmagi/app/repository/RefreshTokenRepository.java
  src/main/java/shop/mulmagi/app/security/CustomAuthenticationProvider.java
  src/main/java/shop/mulmagi/app/service/UserService.java
  src/main/java/shop/mulmagi/app/service/impl/UserServiceImpl.java
  src/main/java/shop/mulmagi/app/util/JwtUtil.java
  src/main/java/shop/mulmagi/app/web/controller/UserController.java
  src/main/java/shop/mulmagi/app/web/dto/UserDto.java
Labels: enhancement

#130 Update: 유저 rental 기록 불러오기 화면 만들기
  src/main/java/shop/mulmagi/app/repository/RentalRepository.java
  src/main/java/shop/mulmagi/app/service/UserService.java
  src/main/java/shop/mulmagi/app/service/impl/UserServiceImpl.java
  src/main/java/shop/mulmagi/app/web/controller/UserController.java
  src/main/java/shop/mulmagi/app/web/dto/UserDto.java
Labels: Refactor

#138 Refactor: User 기능 연결(결제, 알림)
  src/main/java/shop/mulmagi/app/config/SecurityConfig.java
  src/main/java/shop/mulmagi/app/web/controller/NotificationController.java
  src/main/java/shop/mulmagi/app/web/controller/PaymentController.java
Labels: Refactor
